openapi: 3.1
info: A wrapper around networking sites such as meetup
paths:
  - /meetup/search?query=###?length=??:
    get:
      desciption: search for in person meetups in toronto by a certain query
      parameters:
        - query:
          desciption: the query to search for
          required: true
        - length:
          desciption: number of events to return. 20 by default
          required: false
      responses:
        200:
          desciption: list of events
          content:
            application/json:
              schema:
                type: object
                query:
                  type: string
                  desciption: the query string
                  items:
                    type: int32
                  events:
