services:
  backend:
    build: ./backend
    image: shawnyu5/networking_accumulator
    ports:
      - 8000:8000
    hostname: backend
    restart: always

  bot:
    build: ./bot
    image: shawnyu5/networking_bot
    env_file:
      - ./bot/.env
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
