services:
  api:
    build: ./backend
    image: shawnyu5/networking_accumulator
    # ports:
      # - "8000:8000"
    hostname: api
    networks:
      - mynet
    restart: always

  bot:
    build: ./bot
    image: shawnyu5/networking_bot
    env_file:
      - ./bot/.env
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - mynet
    restart: always

networks:
  mynet:
    driver: bridge
