# fly.toml app configuration file generated for networking-accumulator on 2023-05-31T20:33:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "networking-accumulator"
primary_region = "yyz"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
