# fly.toml app configuration file generated for broken-wildflower-7559 on 2023-08-08T17:04:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "broken-wildflower-7559"
primary_region = "yyz"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
