name: Build

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd backend && cargo build --verbose
      - name: Run tests
        run: cd backend && cargo test --verbose

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/checkout@v3

      - name: Build
        run: cd frontend && npm ci && npm run build
