name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd backend && cargo build --verbose
      - name: Run tests
        run: cd backend && cargo test --verbose
  generateRelease:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx npx semantic-release
