name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build:
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v3
    # - name: Build
      # run: cd backend && cargo build --verbose
    # - name: Run tests
      # run: cd backend && cargo test --verbose
  generateRelease:
    runs-on: ubuntu-latest
    # needs:
      # - build
    steps:
      - uses: actions/checkout@v3
      - name: semantic release
        run: npx npx semantic-release

